import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'
import LanguageModal from '../components/LanguageModal'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [modal, setModal] = useState<boolean>(false);

  const onModal = () => {
    setModal(true);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Lee Ji Woong - Principle & Solid</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/codingOnTheBed.png" />
      </Head>

      <main className={styles.main}>
        <div className={styles.introduce_name}>
          Lee Ji Woong
        </div>
        <div className={styles.introduce_text_1}>
          Principle
        </div>
        <div className={styles.introduce_text_2}>
          &
        </div>
        <div className={styles.introduce_text_3}>
          Solid
        </div>
        <div className={styles.settings} onClick={onModal}>
          <a>Explore</a>
        </div>
        {
          modal
          ? (
            <LanguageModal />
          )
          : (
            null
          )
        }
      </main>
    </div>
  )
}

export default Home
